/**
 * Demo data for offline/demo mode (no MongoDB required)
 * Used when backend is unavailable
 */

export const DEMO_USER = {
  _id: 'demo-user-001',
  name: 'Alex Johnson',
  email: 'demo@taskflowx.com',
  xp: 2450,
  level: 7,
  levelTitle: 'Master',
  xpProgress: 64,
  streak: 12,
  longestStreak: 21,
  totalTasksCompleted: 87,
  achievements: [
    { id: 'first_task', name: 'First Step', icon: '🎯', unlockedAt: new Date() },
    { id: 'tasks_10', name: 'Getting Started', icon: '🚀', unlockedAt: new Date() },
    { id: 'tasks_50', name: 'Task Master', icon: '⚡', unlockedAt: new Date() },
    { id: 'week_warrior', name: 'Week Warrior', icon: '🔥', unlockedAt: new Date() },
    { id: 'rising_star', name: 'Rising Star', icon: '⭐', unlockedAt: new Date() },
    { id: 'streak_expert', name: 'Streak Expert', icon: '💎', unlockedAt: new Date() },
  ],
};

export const DEMO_TASKS = [
  {
    _id: 'task-001',
    title: 'Design new product landing page',
    description: 'Create a stunning, conversion-optimized landing page for the Q3 product launch.',
    priority: 'critical',
    category: 'Work',
    status: 'inprogress',
    kanbanColumn: 'inprogress',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    color: '#6366f1',
    tags: ['design', 'launch', 'q3'],
    estimatedTime: 180,
    subtasks: [
      { title: 'Research competitor pages', completed: true },
      { title: 'Create wireframes', completed: true },
      { title: 'Design hero section', completed: false },
      { title: 'Mobile responsive layout', completed: false },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'task-002',
    title: 'Write Q3 performance review',
    description: 'Compile metrics, achievements and goals for the quarterly review meeting.',
    priority: 'high',
    category: 'Work',
    status: 'todo',
    kanbanColumn: 'todo',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    color: '#f97316',
    tags: ['review', 'metrics'],
    estimatedTime: 90,
    subtasks: [],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'task-003',
    title: 'Run 5km — Morning run',
    description: 'Maintain daily exercise habit. Run the park trail route.',
    priority: 'medium',
    category: 'Health',
    status: 'todo',
    kanbanColumn: 'todo',
    dueDate: new Date().toISOString(),
    completed: false,
    color: '#10b981',
    tags: ['fitness', 'health'],
    estimatedTime: 40,
    subtasks: [],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'task-004',
    title: 'Read "Atomic Habits" — chapter 7-9',
    description: 'Continue the book reading habit. Take notes on key insights.',
    priority: 'low',
    category: 'Learning',
    status: 'todo',
    kanbanColumn: 'todo',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    color: '#a855f7',
    tags: ['reading', 'self-improvement'],
    estimatedTime: 45,
    subtasks: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'task-005',
    title: 'Fix login page bug on Safari',
    description: 'Users on Safari 17 report the login form submission is broken.',
    priority: 'critical',
    category: 'Work',
    status: 'review',
    kanbanColumn: 'review',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    color: '#f43f5e',
    tags: ['bug', 'frontend', 'safari'],
    estimatedTime: 60,
    subtasks: [
      { title: 'Reproduce the bug', completed: true },
      { title: 'Identify root cause', completed: true },
      { title: 'Apply fix and test', completed: true },
      { title: 'Code review', completed: false },
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'task-006',
    title: 'Update project documentation',
    description: 'Update README and API docs with the latest changes from v2.1.',
    priority: 'medium',
    category: 'Work',
    status: 'done',
    kanbanColumn: 'done',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed: true,
    color: '#06b6d4',
    tags: ['docs'],
    estimatedTime: 30,
    subtasks: [],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'task-007',
    title: 'Plan team offsite agenda',
    description: 'Coordinate with all team leads and create a full schedule for the offsite.',
    priority: 'high',
    category: 'Work',
    status: 'todo',
    kanbanColumn: 'todo',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    color: '#f59e0b',
    tags: ['team', 'planning'],
    estimatedTime: 120,
    subtasks: [],
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_HABITS = [
  {
    _id: 'habit-001',
    name: 'Morning Run',
    description: '5km every morning before work',
    icon: '🏃',
    color: '#10b981',
    frequency: 'daily',
    streak: 12,
    longestStreak: 21,
    totalCompletions: 34,
    entries: [
      ...Array.from({ length: 7 }, (_, i) => ({
        date: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString(),
        completed: i < 5,
      })),
    ],
  },
  {
    _id: 'habit-002',
    name: 'Read for 30min',
    description: 'Daily reading for personal growth',
    icon: '📚',
    color: '#6366f1',
    frequency: 'daily',
    streak: 7,
    longestStreak: 14,
    totalCompletions: 21,
    entries: [
      ...Array.from({ length: 7 }, (_, i) => ({
        date: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString(),
        completed: i < 4,
      })),
    ],
  },
  {
    _id: 'habit-003',
    name: 'Drink 2L Water',
    description: 'Stay hydrated throughout the day',
    icon: '💧',
    color: '#06b6d4',
    frequency: 'daily',
    streak: 3,
    longestStreak: 10,
    totalCompletions: 18,
    entries: [
      ...Array.from({ length: 7 }, (_, i) => ({
        date: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString(),
        completed: i < 3,
      })),
    ],
  },
];

export const DEMO_ANALYTICS = {
  overview: {
    totalTasks: 7,
    completedTasks: 1,
    pendingTasks: 6,
    overdueTasks: 1,
    completedToday: 2,
    createdToday: 1,
    completionRate: 14,
  },
  user: {
    xp: 2450,
    level: 7,
    streak: 12,
    longestStreak: 21,
    totalTasksCompleted: 87,
    achievements: DEMO_USER.achievements,
  },
  productivityScore: 72,
  dailyTrend: [
    { day: 'Mon', completed: 4, created: 5 },
    { day: 'Tue', completed: 6, created: 4 },
    { day: 'Wed', completed: 3, created: 6 },
    { day: 'Thu', completed: 8, created: 7 },
    { day: 'Fri', completed: 5, created: 3 },
    { day: 'Sat', completed: 2, created: 2 },
    { day: 'Sun', completed: 4, created: 4 },
  ],
  categoryBreakdown: [
    { name: 'Work', total: 4, completed: 1 },
    { name: 'Health', total: 1, completed: 0 },
    { name: 'Learning', total: 1, completed: 0 },
    { name: 'Personal', total: 1, completed: 0 },
  ],
  priorityBreakdown: {
    critical: 2,
    high: 2,
    medium: 2,
    low: 1,
  },
};
